[project]
name = "learn-django"
version = "0.1.0"
description = "I am learning backend django"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.1",
    "pillow>=11.2.1",
]
